  - name: install zabbix-agent
    ansible.builtin.apt:
      name: zabbix-agent
      state: present
      update_cache: yes
    become: yes
  - name: copy config
    template:
      src: /etc/ansible/playbook/roles/deploy_zabbix_agent/files/zabbix-agent-template.conf
      dest: /etc/zabbix/zabbix_agentd.conf
      mode: 0644
    become: yes

  - name: zabbix-agent systemd
    systemd:
      name: zabbix-agent.service
      enabled: yes
      state: started
